configs:
  params:
    application.instanceLabelKey: argocd.argoproj.io/instance

server:
  insecure: true

global:
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "argocd"
      effect: "NoSchedule"
